Traceback (most recent call last):
  File "./encode_validation__vanillaC.py", line 111, in <module>
    pmid = data[idx][0]
IndexError: list index out of range
